force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Team Lead</fullName>
            </value>
            <value>
                <fullName>Associate Developer</fullName>
            </value>
            <value>
                <fullName>Senior Developer</fullName>
            </value>
            <value>
                <fullName>Junior Developer</fullName>
            </value>
            <value>
                <fullName>Trainee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApexToFlow.cls
public class ApexToFlow {
    @InvocableMethod()
    public static List<List<Employee__c>> connectFlow(List<Id> ids) {
        List<List<Employee__c>> masterList = new List<List<Employee__c>>();
        
        if (ids != null && !ids.isEmpty()) {
            List<Employee__c> data= [select Name,Active__c,Position__c,Salary__c,Department__r.Name from Employee__c where Department__c in :ids];
            Map<Id, List<Employee__c>> dataMap = new Map<Id, List<Employee__c>>();
            for (Employee__c employee : data) {
                if (!dataMap.containsKey(employee.Department__c)) {
                    dataMap.put(employee.Department__c, new List<Employee__c>());
                }
                dataMap.get(employee.Department__c).add(employee);
            }
            
            for (Id departmentId : ids) {
                masterList.add(dataMap.get(departmentId));
            }
        }
        
        System.debug('Master List: ' + masterList);
        return masterList;
    }
}