force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmployeeControllerTigApex.cls
public class EmployeeControllerTigApex {
     public static Boolean runTrigger = true;
    public static void empUpdate(Employee__c oldManager, Id depId, Id conId) {
        
        if(runTrigger){
            if (oldManager != null) {
                try {
                    // Set old manager's Active__c to false
                    oldManager.Active__c = false;
                    update oldManager;
    
                    // Update the Department's Manager__c field
                    Department__c department = [
                        SELECT Manager__c 
                        FROM Department__c 
                        WHERE Id = :depId 
                        LIMIT 1
                    ];
                    department.Manager__c = conId;
                    
                    system.debug(department);
                    runTrigger = false;
                   update department;  //looping issue so hold on employee manager update
                } catch (Exception e) {
                    // Log the exception
                    System.debug('Exception: ' + e.getMessage());
                } finally {
                    	runTrigger = true;
                    }
                
            }
        }
    }
}