force-app/main/default/objects/PPF_Account__c/PPF_Account__c.object-meta.xml
<CustomObject>
    <label>PPF Account</label>
    <nameField>
        <displayFormat>PPF-{0000}</displayFormat>
        <label>PPF Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPF Account</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPF_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PPF Account</relationshipLabel>
    <relationshipName>X20</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PPF_Account__c/fields/Maturity_Value__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Value__c</fullName>
    <label>Maturity Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPF_Account__c/fields/Rate_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Interest__c</fullName>
    <defaultValue>1.7</defaultValue>
    <label>Rate of Interest</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPF_Account__c/fields/Time_Period__c.field-meta.xml
<CustomField>
    <fullName>Time_Period__c</fullName>
    <label>Time Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPF_Account__c/fields/Total_Interest__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest__c</fullName>
    <label>Total Interest</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPF_Account__c/fields/Total_Invested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invested_Amount__c</fullName>
    <label>Total Invested Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPF_Account__c/fields/Yearly_Investment__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Investment__c</fullName>
    <label>Yearly Investment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PPFAccountController.cls
public class PPFAccountController {
    @AuraEnabled
    public static void sendPpfAccountDetails(Id ppfAccountId) {
        PPF_Account__c ppfAccount = [SELECT Account__r.Email__c, Yearly_Investment__c, Time_Period__c, Rate_of_Interest__c, Total_Invested_Amount__c, Total_Interest__c, Maturity_Value__c 
                                     FROM PPF_Account__c 
                                     WHERE Id = :ppfAccountId LIMIT 1];
 
        if (ppfAccount.Account__r.Email__c == null) {
            throw new AuraHandledException('Account does not have an email address.');
        }
 
        String subject = 'Your PPF Account Details';
        String body = 'Here are the details of your PPF account:\n\n' +
                      'Yearly Investment: ' + ppfAccount.Yearly_Investment__c + '\n' +
                      'Time Period: ' + ppfAccount.Time_Period__c + '\n' +
                      'Rate of Interest: ' + ppfAccount.Rate_of_Interest__c + '%\n' +
                      'Total Invested Amount: ' + ppfAccount.Total_Invested_Amount__c + '\n' +
                      'Total Interest: ' + ppfAccount.Total_Interest__c + '\n' +
                      'Maturity Value: ' + ppfAccount.Maturity_Value__c;
 
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] { ppfAccount.Account__r.Email__c });
        mail.setSubject(subject);
        mail.setPlainTextBody(body);
 
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}