force-app/main/default/objects/DeletedRecords__c/DeletedRecords__c.object-meta.xml
<CustomObject>
    <label>DeletedRecords</label>
    <nameField>
        <label>Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DeletedRecords</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeletedRecords__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Emp_Count__c.field-meta.xml
<CustomField>
    <fullName>Emp_Count__c</fullName>
    <label>Emp Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeletedEmployeeClass.cls
public class DeletedEmployeeClass {
    public static void deleteEmp(List<DeletedRecords__c> Del,List<Id> ids){
        
        	List<Department__c> depList = [select id,Name from Department__c where id in :ids];
            for(Department__c dep: depList){
                for(DeletedRecords__c delRec: Del){
                    if(delRec.Department__c.equals(dep.id.toString())){
                        delRec.Department__c = dep.Name;
                    }
                }
            }
            insert Del;
    }
    
    public static void insertEmp(List<Id> ids){
        try{
            if(ids.size()>0){
                List<Department__c> department = [select Emp_Count__c,(select id from Employees__r) from Department__c where Id in :ids];
                for(Department__c dep: department){
                    dep.Emp_Count__c = dep.Employees__r.size();
                }
                if(department.size()>0)
                    update department;
            }
        }
        catch(Exception e){}
    }
}